services:
  app:
    build: .
    container_name: node_ts_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm run dev

  redis:
    image: redis:alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
 redis_data:
   driver: local